languageCode = "tr-tr"
title = "erto's blog"
baseURL = "https://kuzgunertugrul.com/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "insanlık hali roller coaster"
  codePenUser = "erto"
