languageCode = "tr-tr"
title = "erto's blog"
baseURL = "https://kuzgunertugrul.com/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "patience you must have, my young Padawan. ~yoda"
  codePenUser = "erto"
